//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; Text=&quot;SUBJECT PERFOMANCE&quot; VerticalAlignment=&quot;Top&quot; TextDecorations=&quot;Underline&quot; FontFamily=&quot;Arial&quot; FontSize=&quot;18&quot;/&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Left&quot; Margin=&quot;30,85,0,0&quot; Text=&quot;CLASS:&quot; VerticalAl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AggregateResult {
            get {
                return ResourceManager.GetString("AggregateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; Text=&quot;BALANCES BY CLASS&quot; VerticalAlignment=&quot;Top&quot; TextDecorations=&quot;Underline&quot; FontFamily=&quot;Arial&quot; FontSize=&quot;18&quot;/&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Left&quot; Margin=&quot;30,83,0,0&quot; Text=&quot;CLASS:&quot; VerticalAli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Balances {
            get {
                return ResourceManager.GetString("Balances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; Text=&quot;CLASS LIST&quot; VerticalAlignment=&quot;Top&quot; TextDecorations=&quot;Underline&quot; FontFamily=&quot;Arial&quot; FontSize=&quot;18&quot;/&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Left&quot; Margin=&quot;30,83,0,0&quot; Text=&quot;CLASS:&quot; VerticalAlignment= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassList {
            get {
                return ResourceManager.GetString("ClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,20,0,0&quot; Text=&quot;{Binding Info.FullName, Source={x:Static Application.Current}}&quot; VerticalAlignment=&quot;Top&quot; FontFamily=&quot;Segoe UI Light&quot; FontSize=&quot;26&quot;/&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,60,0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassMarkList {
            get {
                return ResourceManager.GetString("ClassMarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///           xmlns:local=&quot;clr-namespace:Starehe&quot; 
        ///           xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; Width=&quot;793.76&quot; Height=&quot;1122.56&quot; Background=&quot;White&quot;
        ///           xmlns:sys=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///    &lt;FixedPage.Resources&gt;
        ///        &lt;sys:Double x:Key=&quot;rowHeight&quot;&gt;25&lt;/sys:Double&gt;
        ///    &lt;/FixedPage.Resources&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;Image HorizontalAlignment=&quot;Left&quot; Height= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeavingCert {
            get {
                return ResourceManager.GetString("LeavingCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; Text=&quot;{Binding Info.FullName, Source={x:Static Application.Current}}&quot; VerticalAlignment=&quot;Top&quot; FontFamily=&quot;Segoe UI Light&quot; FontSize=&quot;26&quot;/&gt;
        ///        &lt;StackPanel Orientation=&quot;Horizontal&quot; Margin=&quot;0,70, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentVoucher {
            get {
                return ResourceManager.GetString("PaymentVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Height=&quot;793.76&quot; Width=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Height=&quot;793.76&quot; Width=&quot;1122.56&quot; DataContext=&quot;{Binding Source={x:Static Application.Current}}&quot;&gt;
        ///    &lt;TextBlock HorizontalAlignment=&quot;Left&quot; Margin=&quot;230,36,0,0&quot; Text=&quot;FEES RECEIPT&quot; FontWeight=&quot;Bold&quot; VerticalAlignment=&quot;Top&quot; FontFamily=&quot;Times New Roman&quot; FontSize=&quot;16&quot;/&gt;
        ///       
        ///        &lt;StackPanel Orientat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock   Margin=&quot;0,130,0,0&quot; Text=&quot;FEES RECEIPT&quot; FontWeight=&quot;Bold&quot; VerticalAlignment=&quot;Top&quot; FontFamily=&quot;Times New Roman&quot; FontSize=&quot;16&quot;
        ///                    HorizontalAlignment=&quot;Center&quot;/&gt;
        ///&lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; 
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Receipt2 {
            get {
                return ResourceManager.GetString("Receipt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;           
        ///           xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; Width=&quot;793.76&quot; Height=&quot;1122.56&quot; Background=&quot;White&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,10,0,0&quot; Text=&quot;FEES STATEMENT&quot; VerticalAlignment=&quot;Top&quot; FontWeight=&quot;SemiBold&quot;
        ///                   FontSize=&quot;18&quot;/&gt;
        ///    &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,72,0,0&quot; VerticalAlignment=&quot;Top&quot;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,30,0,0&quot; 
        ///                   Text=&quot;{Binding Info.FullName, Source={x:Static Application.Current}}&quot; 
        ///                   VerticalAlignment=&quot;Top&quot; FontFamily=&quot;Segoe UI Light&quot; FontSize=&quot;26&quot;/&gt;
        ///        
        ///        &lt;Ima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcript {
            get {
                return ResourceManager.GetString("Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FixedPage xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///           Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///    &lt;Grid Width=&quot;793.76&quot; Height=&quot;1122.56&quot;&gt;
        ///        &lt;Border Margin=&quot;10,10,10,30&quot; BorderBrush=&quot;Gray&quot; BorderThickness=&quot;1&quot;/&gt;
        ///        &lt;TextBlock HorizontalAlignment=&quot;Center&quot; Margin=&quot;0,20,0,0&quot; 
        ///                   Text=&quot;{Binding Info.FullName, Source={x:Static Application.Current}}&quot; 
        ///                   VerticalAlig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcript2 {
            get {
                return ResourceManager.GetString("Transcript2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UnreturnedBooks {
            get {
                return ResourceManager.GetString("UnreturnedBooks", resourceCulture);
            }
        }
    }
}
